// `.env.json` is generated by the `npm run build` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  author: 'CNES - CENTRE NATIONAL D\'ETUDES SPATIALES',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: [
	'en-US',
	'fr-FR'
  ]
};
