// `.env.json` is generated by the `npm run build` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  author: 'CNES - CENTRE NATIONAL D\'ETUDES SPATIALES',
  serverUrl: 'http://localhost:8081/cubeExplorer/rest',
  defaultLanguage: 'en-US',
  supportedLanguages: [
	'en-US',
	'fr-FR'
  ],
  imgPath:'../templates/datacube'
};
